### ISSUE TITLE
Cannot load directories with non-English characters

### ISSUE THREAD

**Issue by WGzeyu** [darknight1050/SongLoader#7]
![](https://wgzeyu.gtxcn.com/img/bs/sl1.png)
![](https://wgzeyu.gtxcn.com/img/bs/sl2.jpg)

![](https://wgzeyu.gtxcn.com/img/bs/sl3.png)
![](https://wgzeyu.gtxcn.com/img/bs/sl4.jpg)

**Comment by darknight1050** [comment]
That isn't possible to fix with how quest currently works (based on android/linux)
